spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass

server:
  port: 8001


microservice:
  orders-service:
    endpoints:
      endpoint:
        uri: fake-service